# Generated by Django 3.2.6 on 2021-09-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='description_brand', null=True)),
                ('is_available', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=None)),
                ('updates', models.TextField(default='description_form', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SNACKS', 'Snacks'), ('BISCUITS', 'Biscuits'), ('CHOCOLATES', 'Chocolates'), ('HEALTH', 'Health')], default='Snacks', max_length=20)),
                ('is_available', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentails.brand')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentails.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='brands',
            field=models.ManyToManyField(through='essentails.ItemBrand', to='essentails.Brand'),
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=None)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentails.form')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentails.item')),
            ],
        ),
    ]
