# Generated by Django 3.2.6 on 2021-09-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentails', '0003_auto_20210908_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='useritem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='useritem',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
